[package]
name = "oxidgb_core"
version = "0.1.0"
authors = ["James <jselby@jselby.net>"]

[lib]
name = "oxidgb_core"

[dependencies]
log = "0.3.8"

serde = {version = "1.0.68", default-features = false, features = ["alloc"] }
serde_derive = "1.0.68"

